[package]
name = "water-simulation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.5", features = ["derive"] }
env_logger = "0.10.0"
image = "0.24.6"
log = "0.4.19"
